# Generated by Django 4.0.3 on 2022-03-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=200)),
                ('room_group_name', models.CharField(max_length=200)),
                ('room_id', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
